### ISSUE TITLE
Contest submissions

### ISSUE THREAD

**Issue by PiKeyAr** [PiKeyAr/sadx-dreamcast-dlc#1]
To participate in the contest, upload a video of your playthrough and share the link here. 
The deadline for submissions is September 23rd, 0:00 (UTC).

**Comment by ChrisHighwind** [comment]
https://www.youtube.com/watch?v=X0MvyM5vHVE&feature=youtu.be

**Comment by TrackerTD** [comment]
This is less so me entering the contest and moreso just letting you know it all seems to work fine and dandy on hardware: https://www.youtube.com/watch?v=FagK0TjUa2A&lc=Ugx2eYvRbafajUoBEx94AaABAg

**Comment by jstep32x** [comment]
Here is my video.
https://www.youtube.com/watch?v=4-R1n_ywxjk

**Comment by Resilixia** [comment]
28:39
[https://youtu.be/UDv5-qN4z_k](url)

**Comment by airchomp** [comment]
![AC_ScoreSoFar](https://user-images.githubusercontent.com/31281923/93880694-dd433d80-fcab-11ea-83e1-6691630ab934.jpg)
Sorry I couldn't exactly get a video of it on real hardware yet, but I did take a photo of my best time. Even if it doesn't count, I'm glad to have played it! Thank you!

**Comment by PiKeyAr** [comment]
The deadline has been extended indefinitely. The contest will close when there are at least 10 submissions. Depending on the entries I may end up giving out two prizes: 


1) "Best overall" for the fastest time, which permits usage of emulators, TAS runs, third-party controllers for the Dreamcast etc.
2) "Best genuine" for runs made on hardware using authentic Dreamcast controllers.


Even though the game saves the result of the run on the memory card, a video recording of the run is necessary in order to qualify as a contest entry. Dreamcast hardware mods such as DC-HDMI, GDEMU etc. qualify for the 2nd category as long as the controller is original. Non-genuine copies of Sonic Adventure also qualify as long as they don't have hacks that result in advantages to the player.

**Comment by Resilixia** [comment]
So it basically gonna take forever now with these 4 missing submissions...

**Comment by PiKeyAr** [comment]
I guess so... Or I could just close it at this point and give the prize to @jstep32x.

**Comment by PiKeyAr** [comment]
@jstep32x please let me know your Steam ID (here or on [x-hax Discord](https://discord.com/invite/gqJCF47)) to claim your copy of SADX Steam.

**Comment by jstep32x** [comment]
@PiKeyAr Great! I'll join the discord to claim it.

**Comment by axel12isai** [comment]
._.xd
