### ISSUE TITLE
Text won't show up if the message option is set to Voice Only

### ISSUE THREAD

**Issue by Ducky27** [PiKeyAr/sadx-dreamcast-dlc#4]
I don't really like subtitles over spoken dialogue so I turn subs off in most cases and this also applies to Sonic Adventure. Something I like is that it still keeps the subtitles for the NPC lines that aren't voiced. However, that doesn't happen with this mod. You have to set the game to Voice and Text to be able to read the subtitles for objects exclusive to this mod. I would really like if that was changed so I could see the subtitles on Voice Only (and it would make it more consistent with the rest of the game).

**Comment by PiKeyAr** [comment]
This should be fixed now in the latest version
